
build: Pokemon_sql_server.class

Pokemon_sql_server.class: Pokemon_sql_server.java
	javac Pokemon_sql_server.java

run: Pokemon_sql_server.class
	java -cp .:mssql-jdbc-11.2.0.jre11.jar Pokemon_sql_server

clean:
	rm Pokemon_sql_server.class
